version: '3'
services:
  node:
    image: 'node:12.16.3'
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - ./api:/home/node/app
      - ./apidata/public:/home/node/app/src/public
    ports:
      - '3000:3000'
    command: 'sh -c "npm install && npm run build && cd build && node index.js"'
